### ISSUE TITLE
TEST REST API 21:06

### ISSUE THREAD

**Issue by dro42** [SAMJ-CSDC26BB/SAMJ-Django-TBC#57]
```yaml
        - URL: 
        - `http://localhost:8000/support/`
        - Short Description: dagsgrtwsg
        - Detailed Description: shtshsh
        - Steps to Reproduce: wrthwrth
        - Expected Results: wrthwrthw
        - Actual Results: rthwrthwt5r
        
```
