### ISSUE TITLE
Test the support ticket

### ISSUE THREAD

**Issue by dro42** [SAMJ-CSDC26BB/SAMJ-Django-TBC#58]
```yaml
- Name: Technical User

- Name: 36367365735
- URL: http://localhost:8000/support/
- Short Description: support ticket not created
- Detailed Description: support ticket not createdsupport ticket not createdsupport ticket not createdsupport ticket not createdsupport ticket not createdsupport ticket not created
- Steps to Reproduce: support ticket not createdsupport ticket not createdsupport ticket not createdsupport ticket not createdsupport ticket not createdsupport ticket not createdsupport ticket not createdsupport ticket not createdsupport ticket not createdsupport ticket not createdsupport ticket not createdsupport ticket not createdsupport ticket not createdsupport ticket not createdsupport ticket not createdsupport ticket not createdsupport ticket not createdsupport ticket not createdsupport ticket not createdsupport ticket not createdsupport ticket not createdsupport ticket not createdsupport ticket not createdsupport ticket not created
- Expected Results: should create the ticket
- Actual Results: does not create the ticket
```
