### ISSUE TITLE
Testing now

### ISSUE THREAD

**Issue by samj-technical-user** [SAMJ-CSDC26BB/SAMJ-Django-TBC#59]
```yaml
- Name: Max Mustermann

- Telephone: 34563635463
- URL: http://localhost:8000/support/
- Short Description: etwqt
- Detailed Description: wertwert
- Steps to Reproduce: qertqtq
- Expected Results: qertqwertqe
- Actual Results: eqrtqwrtq
```
