### ISSUE TITLE
Issue with Support Ticket view

### ISSUE THREAD

**Issue by samj-technical-user** [SAMJ-CSDC26BB/SAMJ-Django-TBC#61]
```yaml
- Name: The student
- E-Mail: student@leraning.edu
- Telephone: 111111111
- URL: http://localhost:8000/support/ticket
- Short Description: cannot see my ticket
- Detailed Description: I cannot see my ticket,  was it created?
- Steps to Reproduce: got to http://localhost:8000/support/ and fill out
- Expected Results: ticket to be created
- Actual Results: ticket has to be created
```
