### ISSUE TITLE
[SUPPORT][BUG] Telephone system doesn't forward number

### ISSUE THREAD

**Issue by samj-technical-user** [SAMJ-CSDC26BB/SAMJ-Django-TBC#62]
```yaml
Contact Details (optional):
- Name: Some dude
- E-Mail: this.dude@google.com
- Telephone: 123456789

Issue Details:
- URL: http://samj.com/home
- Short Description: Telephone system doesn't forward number
- Detailed Description: Telephone system doesn't forward the number 123456789
- Steps to Reproduce: click on forwards
then this 
then that
- Expected Results: forward the number
- Actual Results: does not forward the num
```
