### ISSUE TITLE
[SUPPORT][BUG] Login Not working

### ISSUE THREAD

**Issue by samj-technical-user** [SAMJ-CSDC26BB/SAMJ-Django-TBC#77]
```yaml
Contact Details (optional):


Issue Details:
- URL: http://localhost/login
- Short Description: Login Not working
- Detailed Description: Login Not working
- Steps to Reproduce: 1. click login button
- Expected Results: login successful
- Actual Results: login not working
```
